[package]
name = "tilepad-cli"
description = "CLI for developing tilepad plugins"
version = "0.0.0"
edition = "2024"
readme = "README.md"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/tilepad/tilepad-cli"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
eyre = "0.6.12"
color-eyre = "0.6"
zip = "2.4.2"
walkdir = "2.5.0"

node-semver = "2.2.0"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8.20"

# Validation
garde = { version = "0.22.0", features = ["full"] }
strum = { version = "0.27.1", features = ["derive"] }
dirs = "6.0.0"


[[bin]]
name = "tilepad"
path = "src/main.rs"
